spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isa_database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate.ddl-auto: update

server.servlet.context-path: /api

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

properties:
  jwtSecret: Jwt331secret1
  jwtExpirationInMs: 604800000
  maxAgeSecs: 3600
  frontBaseUrl: 'http://localhost:3000'

