spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isa_database?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
  jpa:

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    generate-ddl: true
    hibernate.ddl-auto: update

  mail:
    properties:
      starttls:
        enable: true
        required: true
      smtp:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
      debug: true
    host: smtp.gmail.com
    port: 587
    username: bookingums@gmail.com
    password: bookingums
    protocol: smtp

server.servlet.context-path: /api

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

properties:
  jwtSecret: Jwt331secret1
  jwtExpirationInMs: 604800000
  maxAgeSecs: 3600
  frontBaseUrl: 'http://localhost:3000'